### PR TITLE
Edit buffer support (pt1)

### PR DESCRIPTION
**Pull request by alexbruy**
Initial implementation of the "undo" and vector layer edit buffer support. Currently works only when editing geometry of the existing feature.

### CODE REVIEW

**Comment by tomasMizera** [comment]
@alexbruy can you please merge master here? iOS build should work then :)

**Comment by tomasMizera** [comment]
There is some crash in lookForVertex method

**Comment by tomasMizera** [comment]
It crashes also for me when I identify 3rd / 4th feature

**Comment by alexbruy** [comment]
No crashes here on identify. I clicked over 20 features and it still works.

**Comment by alexbruy** [comment]
Regarding crash in test, it is expected as this PR does not support creating new features. Only editing existing geometries.

**Pull request merged**
