### PR TITLE
Removed Qt.inputMethod.commit() for tests

### PR DESCRIPTION
**Pull request by iiLubos**
Just for tests, if it is needed to use Qt.inputMethod.commit() method

### CODE REVIEW

**Comment by tomasMizera** [comment]
@jozef-budac / @PatrikMizera, can we please test text and number inputs? We need to test different keyboards as well. The goal is to see if everything is working fine as previously (e.g. form validations)

**Comment by jozef-budac** [comment]
TI @tomasMizera . I have tested on Android 11, 13, and iOS and on iOS keyboard, Gboad, and Samsung keyboard and found nothing problematic. Everything worked ok.

**Comment by jozef-budac** [comment]
I just found one problem with relations. The app freezes when you create a parent and from it the child. 
Scenario:
1) Open project tc05_relations
2) Hit record on the district, add 3 points, and hit done so the form opens
3) Write a name on the form 
4) Hit +Add to add a child. On the map add 3 points and hit Done -> the app freezes

Screen recording:
https://drive.google.com/file/d/1lZa8aZelJV1xNAxHCXUJmB9W-Hr0pyOR/view?usp=sharing

**Comment by tomasMizera** [comment]
This change seems very dangerous atm. We will revisit within redesign

**Pull request closed without merging**
