### PR TITLE
proj9 support

### PR DESCRIPTION
**Pull request by PeterPetrik**
- bump input-SDKs: updated zxing, libspatialite, proj, qca
- replace proj assets with proj9 from QGIS 3.22

for testing @jozef-budac, definitely: qrcodes, all projection tests, we now should support TIF files for projection as well as old PROJ6 format. It would be good to add TIF file test to proj suite

@alex-cit would be good to update docs to note than now we should support TIF datum shift grids.

follow up from https://github.com/MerginMaps/input-sdk/issues/58
fix https://github.com/MerginMaps/input/issues/2105
related to https://github.com/MerginMaps/qgis-mergin-plugin/issues/444
related to https://github.com/MerginMaps/input/issues/2178
fix https://github.com/MerginMaps/input/issues/1735

Note: linux ubuntu 22.04 is on PROJ8 with different database version, so Linux developers need to replace proj.db with their proj.db to avoid any runtime PROJ errors for the moment (WIP, but difficult to fix: https://github.com/MerginMaps/input-sdk/pull/77)

### CODE REVIEW

**Comment by jozef-budac** [comment]
Two projects are not working:
1) https://app.merginmaps.com/projects/input-testing/tc06_geotiff_jpg/tree
2) https://app.merginmaps.com/projects/input-testing/tc06_online_cog/tree

**Review by tomasMizera — APPROVED** [review]
It is more a matter of testing, these changes are just in proj-related files.

**Comment by PeterPetrik** [comment]
@jozef-budac iOS or Android? can you try with 2.56.220806083431

**Comment by PeterPetrik** [comment]
[/input-testing/tc06_geotiff_jpg/tree](https://app.merginmaps.com/projects/input-testing/tc06_geotiff_jpg/tree)

```
2022-08-09 06:59:53.664164+0200 Input[2976:44480] Logged warning: Loading a file that was saved with a newer version of qgis (saved in 3.23.0-Master, loaded in 3.22.6-Białowieża). Problems may occur.
Warning 1: /Users/peter/Projects/quick/input/app/android/assets/qgis-data/projects/tc06_geotiff_jpg/rrr.tif:JPEG compression support is not configured
ERROR 1: Cannot open TIFF file due to missing codec.
2022-08-09 06:59:53.714382+0200 Input[2976:44480] "2022-08-09T04:59:53.714Z QGIS : Warning: 1 unavailable layers found:\n"
2022-08-09 06:59:53.714625+0200 Input[2976:44480] "2022-08-09T04:59:53.714Z QGIS : Warning:  * ./rrr.tif\n"
2022-08-09 06:59:53.765100+0200 Input[2976:44480] "2022-08-09T04:59:53.765Z InputPROJ: fallbackOperationOccurredReported: \n"
2022-08-09 06:59:53.766955+0200 Input[2976:44480] "2022-08-09T04:59:53.766Z project loading: WARNING: The following layers are invalid: rrr\n"
```

**Comment by jozef-budac** [comment]
@PeterPetrik I can see  2.56.220806083431 in testflight. Can you please recheck the build is shared for testing?

**Comment by PeterPetrik** [comment]
@jozef-budac can you please retest?

**Comment by jozef-budac** [comment]
There are no more problems with tiff files. I also retested all other projections and also QR code functionality and it works fine

**Comment by PeterPetrik** [comment]
@jozef-budac great news! can you please make sure we have a test-case in our manual testing that contains TIF datum (maybe explicitely name it in the test-name, so in the future we know what is broken). Thanks!

**Comment by jozef-budac** [comment]
@PeterPetrik yes. I can do that. Can [c06_geotiff_jpg/tree](https://app.merginmaps.com/projects/input-testing/tc06_geotiff_jpg/tree) be used for this purpose?

**Comment by jozef-budac** [comment]
Two new projects were created for testing shifts:
[Datum shift tiff](https://app.merginmaps.com/projects/input-testing/tc10_datumshift_tiff/tree)
[datum shift gsb](https://app.merginmaps.com/projects/input-testing/tc10_datumshift_gsb/tree)

With both of them input shows error on the beginning with the missing PROJ file, but after restart of the app, no more errors were shown

**Comment by PeterPetrik** [comment]
That is correct behaviour. Merge away!

**Pull request merged**
