### PR TITLE
use zipped QGIS project file by default

### PR DESCRIPTION
**Pull request by PeterPetrik**
fix CU-861mt46b3

### CODE REVIEW

**Comment by PeterPetrik** [comment]
unrelated test errors

**Comment by tomasMizera** [comment]
I'd like to ask @wonder-sk, @uclaros or @alexbruy for review here, they have more expertise with the QGIS API.

**Comment by PeterPetrik** [comment]
Fix was suggested by @wonder-sk

**Comment by tomasMizera** [comment]
Cool, we can merge once he approves (Note this is the related ticket: https://app.clickup.com/t/861mt46b3)

**Review by wonder-sk — APPROVED** [review]
The code looks good :-)

**Pull request merged**
